/**
 * Created by liubeijing on 16/8/13.
 */
module.exports = {
    actionType:{
        IMCOMPLETED_UPDATE:'IMCOMPLETED_UPDATE',
        IMCOMPLETED_CREATE:'IMCOMPLETED_CREATE',
        IMCOMPLETED_DELETE:'IMCOMPLETED_DELETE',
        COMPLETED_UPDATE:'COMPLETED_UPDATE',
        COMPLETED_CREATE:'COMPLETED_CREATE',
        COMPLETED_DELETE:'COMPLETED_DELETE',
        TOGGLE_COMPLETED:'TOGGLE_COMPLETED',
        TOGGLE_IMCOMPLETED:'TOGGLE_IMCOMPLETED'
    },
    eventType:{
        IMCOMPLETED_UPDATE:'IMCOMPLETED_UPDATE',
        IMCOMPLETED_CREATE:'IMCOMPLETED_CREATE',
        IMCOMPLETED_DELETE:'IMCOMPLETED_DELETE',
        COMPLETED_UPDATE:'COMPLETED_UPDATE',
        COMPLETED_CREATE:'COMPLETED_CREATE',
        COMPLETED_DELETE:'COMPLETED_DELETE',
        TOGGLE_COMPLETED:'TOGGLE_COMPLETED',
        TOGGLE_IMCOMPLETED:'TOGGLE_IMCOMPLETED'
    }
};